# Generated by Django 3.1.6 on 2021-02-18 16:27

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210218_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='TMT', max_digits=14, verbose_name='Amount'),
        ),
    ]
