# Generated by Django 3.1.6 on 2021-02-18 16:32

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210218_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='TMT', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('1.00'))], verbose_name='Amount'),
        ),
    ]
