# Generated by Django 3.1.6 on 2021-02-19 04:54

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210218_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='TMT', max_digits=14, verbose_name='Amount'),
        ),
    ]
